import type { Article } from '../types';

export const article: Article = {
    slug: 'a1-digitaal-2026-nieuwe-eu-afspraken',
    title: 'A1 in 2026: digitale attesten, nieuwe EU-afspraken en Oost-Europese ploegen',
    description:
        'De A1-verklaring wordt digitaal en de Europese coördinatieregels gaan op de schop. Wat betekent dat concreet voor een hoofdaannemer die met Oost-Europese ploegen werkt?',
    date: '2026-08-20',
    author: 'Constructief',
    authorIsOrganization: true,
    category: 'Compliance',
    keywords: ['A1 verklaring 2026', 'digitaal A1', 'ESSPASS', 'detachering Oost-Europa', 'posted workers'],
    readingMinutes: 7,
    image: '/images/news/a1-digitaal-2026-nieuwe-eu-afspraken.png',
    blocks: [
        { type: 'p', text: 'Voor een hoofdaannemer met een Poolse, Roemeense of Slowaakse ploeg op de werf is de A1-verklaring het belangrijkste document in het hele dossier. Het bewijst dat de werknemer in zijn thuisland sociaal verzekerd blijft terwijl hij tijdelijk in België werkt. Zolang die verklaring klopt, is er niets aan de hand. Klopt ze niet, dan is het niet de ploeg die het probleem heeft — het is uw werf.' },
        { type: 'p', text: 'Precies daarom is het relevant dat er op twee fronten beweging zit: de Europese coördinatieregels voor detachering worden herzien, en de A1-verklaring wordt gedigitaliseerd. Hieronder wat er speelt en wat u er vandaag mee moet doen.' },
        { type: 'h2', text: 'Wat er op Europees niveau verandert' },
        { type: 'p', text: 'De Europese coördinatie van sociale zekerheid — het kader dat bepaalt welk land sociaal verzekerd is bij grensoverschrijdend werk — wordt hervormd. Over een pakket aanpassingen bereikten de EU-instellingen een voorlopig akkoord, met als doel de regels eenvoudiger en beter controleerbaar te maken voor werkgevers én inspecties.' },
        { type: 'p', text: 'Daarnaast loopt het project rond de Europese sociale zekerheidspas, in de sector bekend als ESSPASS. Het idee is dat een A1 niet langer een losse PDF is die iemand kan doorsturen, maar een digitaal, verifieerbaar gegeven dat een inspecteur — of een aannemer — in real time kan controleren.' },
        { type: 'ul', items: [
            'Vandaag: een A1 is meestal een document dat u als kopie in een map bewaart.',
            'De richting: een digitaal attest dat controleerbaar is op echtheid en geldigheid.',
            'Gevolg voor de werf: minder ruimte voor vervalste of verkeerd opgemaakte attesten, en meer datagestuurde controles.',
        ] },
        { type: 'p', text: 'Dat is op termijn goed nieuws voor wie correct werkt: een digitale verificatie maakt het verschil tussen een echte en een onechte ploeg veel sneller zichtbaar. Het betekent alleen wel dat u er niet meer mee wegkomt om "een A1 in de map" te hebben die inhoudelijk niet klopt.' },
        { type: 'h2', text: 'Waarom dit vooral de bouw raakt' },
        { type: 'p', text: 'De bouw is bij uitstek de sector waarin detachering, onderaanneming en ketens samenkomen: een hoofdaannemer, een tussenpartij, een buitenlandse werkgever en een ploeg op de werf. Europese en nationale inspecties richten hun acties dan ook expliciet op bouwwerven, en stemmen die grensoverschrijdend op elkaar af via de Europese Arbeidsautoriteit.' },
        { type: 'p', text: 'In de praktijk zien we dat patroon terug in handhavingscampagnes in verschillende lidstaten, waarbij tientallen tot honderden overtredingen per actie worden vastgesteld — vaak precies op de punten die bij detachering misgaan: attesten die niet overeenkomen met de mensen op de werf, meldingen die te laat of voor de verkeerde werf gebeuren, en registraties die niet kloppen.' },
        { type: 'quote', text: 'Een A1 is geen formaliteit in een map. Het is het bewijs dat de ploeg op uw werf legaal werkt.' },
        { type: 'h2', text: 'Wat u vandaag moet doen (ongeacht de timing van de hervorming)' },
        { type: 'p', text: 'U hoeft niet te wachten op nieuwe regelgeving om uw risico te verlagen. Deze punten gelden nu al en blijven gelden na elke hervorming:' },
        { type: 'ul', items: [
            'Vraag een A1 per persoon, niet één document voor de hele ploeg.',
            'Controleer of naam, geboortedatum en periode overeenkomen met de werknemer en met de opdracht.',
            'Let op de geldigheidsduur van de detachering: een A1 die verlopen is, is geen A1.',
            'Controleer of het attest het juiste land en de juiste werkgever vermeldt.',
            'Herhaal de controle bij verlenging, bij een nieuwe werf en bij elke wijziging in de ploeg.',
            'Bewaar alles per ploeg en per project, inclusief het bewijs dat u zelf gecontroleerd heeft.',
        ] },
        { type: 'p', text: 'Wie deze routine heeft, is voorbereid op de digitalisering in plaats van erdoor verrast. Wie alleen op de belofte van een tussenpartij vertrouwt, ontdekt het probleem meestal op het slechtst mogelijke moment.' },
        { type: 'h2', text: 'Wat u mag verwachten van een serieuze partner' },
        { type: 'p', text: 'Een leverancier van bouwploegen die zijn zaakjes op orde heeft, levert de attesten aan bij de start — niet na aandringen, en niet halverwege het project. Vraag bij de offerte al welke documenten standaard meegeleverd worden en wie verantwoordelijk is als er iets ontbreekt.' },
        { type: 'ul', items: [
            'A1 per werknemer, aangeleverd vóór de eerste werkdag.',
            'Limosa-melding met de juiste werf en periode.',
            'Checkinatwork-registratie geregeld en afgesproken.',
            'Verzekering arbeidsongevallen op naam van de werkgever.',
        ] },
        { type: 'p', text: 'Zo maakt u van compliance geen discussie achteraf, maar een voorwaarde bij de start. Dat is precies wat de Europese hervormingen beogen — en wat u vandaag al kunt afdwingen.' },
    ],
    related: [
        { label: 'A1 en Limosa: wat u moet checken vóór een ploeg start', href: '/nieuws/a1-limosa-check-hoofdaannemer' },
        { label: 'Ketenaansprakelijkheid: de nieuwe zorgvuldigheidsplicht in de bouw', href: '/nieuws/ketenaansprakelijkheid-2026-zorgvuldigheidsplicht' },
        { label: 'Zwartwerk op de werf vermijden: checklist', href: '/nieuws/zwartwerk-vermijden-checklist' },
        { label: 'Gescreende bouwploegen voor aannemers', href: '/werkgevers' },
    ],
    cta: {
        title: 'Ploegen waarvan de A1 vooraf in orde is',
        text: 'Wij leveren Oost-Europese ploegen met A1, Limosa en Checkinatwork geregeld — u controleert, u jaagt niet.',
        label: 'Bekijk onze aanpak voor aannemers',
        href: '/werkgevers',
    },
};
