import type { Article } from '../types';

export const article: Article = {
    slug: 'ketenaansprakelijkheid-2026-zorgvuldigheidsplicht',
    title: 'Ketenaansprakelijkheid in de bouw: de nieuwe zorgvuldigheidsplicht vanaf 2026',
    description:
        'Van "u moet controleren" naar "u moet kunnen aantonen dat u gecontroleerd heeft". Wat de nieuwe zorgvuldigheidsplicht voor risicosectoren betekent voor hoofdaannemers die met onderaannemers werken.',
    date: '2026-08-22',
    author: 'Constructief',
    authorIsOrganization: true,
    category: 'Risico & compliance',
    keywords: ['ketenaansprakelijkheid 2026', 'zorgvuldigheidsplicht bouw', 'onderaanneming aansprakelijkheid', 'schijnconstructies'],
    readingMinutes: 7,
    image: '/images/news/ketenaansprakelijkheid-2026.webp',
    blocks: [
        { type: 'p', text: 'Jarenlang was de boodschap aan hoofdaannemers: controleer uw onderaannemers. Nieuw is dat die verwachting in een aantal landen en regio\'s verschuift van een morele plicht naar een wettelijke zorgvuldigheidsplicht: u moet niet alleen controleren, u moet kunnen aantonen dát u gecontroleerd heeft.' },
        { type: 'p', text: 'Dat verschil lijkt klein, maar het verandert alles aan hoe u met onderaannemers werkt. Een contractclausule waarin de onderaannemer verklaart alles in orde te hebben, is geen zorgvuldigheid. Een dossier per ploeg is dat wel.' },
        { type: 'h2', text: 'Wat er aan het veranderen is' },
        { type: 'p', text: 'In België wordt de ketenaansprakelijkheid voor risicosectoren — en de bouw is zo\'n sector — aangescherpt met een expliciete zorgvuldigheidsverplichting. In Nederland komt daar een extra laag bij: de introductie van een toelatingsplicht voor het ter beschikking stellen van arbeidskrachten, wat betekent dat u moet weten of de partij die mensen levert daarvoor überhaupt toegelaten is.' },
        { type: 'p', text: 'Ook op Europees niveau wordt de keten strakker: strengere regels rond illegale tewerkstelling in de bouw, en grensoverschrijdende inspecties die specifiek op bouwwerven zijn gericht. De richting is overal dezelfde — de verantwoordelijkheid schuift op naar de partij die de opdracht geeft.' },
        { type: 'ul', items: [
            'België: zorgvuldigheidsplicht en ketenaansprakelijkheid in risicosectoren, waaronder de bouw.',
            'Nederland: toelatingsplicht voor het ter beschikking stellen van arbeidskrachten.',
            'EU: hervorming van detacheringsregels en intensievere grensoverschrijdende controles.',
        ] },
        { type: 'h2', text: 'Wat een zorgvuldigheidsplicht concreet van u vraagt' },
        { type: 'p', text: 'Zorgvuldigheid is geen gevoel, het is een dossier. In de praktijk komt het neer op vier dingen: u weet wie er werkt, u weet onder welke voorwaarden, u heeft dat gecontroleerd, en u kunt dat aantonen.' },
        { type: 'ul', items: [
            'Identiteit en werkgever: van elke persoon op de werf weet u wie de werkgever is.',
            'Legale tewerkstelling: A1 per werknemer, Limosa-melding, Checkinatwork-registratie.',
            'Toelating en inschrijving: is de partij die de mensen levert bevoegd om dat te doen?',
            'Bewijs van controle: een kopie per document, per ploeg, per project — met datum.',
        ] },
        { type: 'p', text: 'Het gaat er niet om dat u het werk van de inspectie overneemt. Het gaat erom dat u kunt aantonen dat u niet blind heeft vertrouwd op een partij die het niet naleefde.' },
        { type: 'quote', text: 'Niet controleren is geen neutrale keuze. Zonder dossier is het uw woord tegen dat van de keten.' },
        { type: 'h2', text: 'Waarom handhaving juist nu scherper wordt' },
        { type: 'p', text: 'Inspecties werken steeds minder op basis van losse tips en steeds meer op basis van data. De registratie op de werf, de meldingen en de attesten vormen samen een beeld dat automatisch afwijkingen blootlegt. Voeg daarbij grensoverschrijdende samenwerking tussen inspectiediensten, en je krijgt campagnes waarin in korte tijd vele tientallen overtredingen op bouwwerven worden vastgesteld.' },
        { type: 'p', text: 'Dat betekent dat de kans dat een niet-nalevende ploeg in uw keten wordt opgemerkt, niet meer afhangt van geluk. Ze hangt af van of iemand de data leest — en dat gebeurt steeds vaker.' },
        { type: 'h2', text: 'Praktisch: zo bouwt u uw dossier op' },
        { type: 'p', text: 'U hoeft hier geen systeem voor te kopen. Een vaste werkwijze per project volstaat, als u ze consequent toepast.' },
        { type: 'ul', items: [
            'Maak één standaard documentenlijst en gebruik die bij élke nieuwe ploeg.',
            'Koppel de start van de werken aan de volledigheid van het dossier.',
            'Controleer niet alleen of documenten bestaan, maar of ze kloppen met de mensen op de werf.',
            'Herhaal de controle bij uitbreiding van de ploeg, bij een nieuwe werf en bij verlenging.',
            'Bewaar alles op één plaats per project, inclusief de datum waarop u controleerde.',
            'Leg contractueel vast wie welke documenten levert en wat er gebeurt als ze ontbreken.',
        ] },
        { type: 'h2', text: 'Wat dit betekent voor uw inkoopkeuzes' },
        { type: 'p', text: 'De nieuwe context verandert de vraag die u aan een leverancier stelt. Niet meer "kunt u mensen leveren?", maar "kunt u aantonen dat uw mensen legaal en gedocumenteerd op mijn werf staan, en levert u dat vóór de start aan?".' },
        { type: 'p', text: 'Partijen die dat standaard doen, kosten misschien iets meer in het uurtarief en besparen u een veelvoud aan risico, stilstand en administratieve rompslomp. Partijen die het niet kunnen, zijn precies de partijen waar de nieuwe regels op mikken.' },
        { type: 'ul', items: [
            'Vraag het documentenpakket op bij de offerte, niet bij de start.',
            'Laat de leverancier aantonen dat hij bevoegd is om arbeidskrachten ter beschikking te stellen.',
            'Spreek af binnen welke termijn ontbrekende documenten worden aangevuld.',
            'Neem de volledigheid van het dossier op als voorwaarde in de overeenkomst.',
        ] },
        { type: 'p', text: 'Zo maakt u van ketenaansprakelijkheid een inkoopcriterium in plaats van een juridisch risico. Dat is exact wat de nieuwe regelgeving beoogt.' },
    ],
    related: [
        { label: 'A1 in 2026: digitale attesten en nieuwe EU-afspraken', href: '/nieuws/a1-digitaal-2026-nieuwe-eu-afspraken' },
        { label: 'A1 en Limosa: wat u moet checken vóór een ploeg start', href: '/nieuws/a1-limosa-check-hoofdaannemer' },
        { label: 'Zwartwerk op de werf vermijden: checklist', href: '/nieuws/zwartwerk-vermijden-checklist' },
        { label: 'Gescreende bouwploegen voor aannemers', href: '/werkgevers' },
    ],
    cta: {
        title: 'Een partner die uw dossier compleet maakt',
        text: 'Wij leveren ploegen met A1, Limosa en Checkinatwork vooraf geregeld — zodat uw zorgvuldigheidsplicht geen zoektocht wordt.',
        label: 'Bekijk onze aanpak voor aannemers',
        href: '/werkgevers',
    },
};
