import type { Article } from '../types';

export const article: Article = {
    slug: 'kosten-bouwploeg-per-uur',
    title: 'Wat bepaalt de prijs van een bouwploeg per uur?',
    description:
        'Een all-in uurprijs voor een bouwploeg bestaat uit meer dan loon. Zo leest u een offerte, vergelijkt u aanbieders eerlijk en voorkomt u verrassingen op de eindafrekening.',
    date: '2026-08-14',
    updated: '2026-08-18',
    author: 'Constructief',
    authorIsOrganization: true,
    category: 'Kosten & planning',
    keywords: ['bouwploeg prijs', 'uurtarief bouwploeg', 'kostprijs onderaannemer'],
    readingMinutes: 6,
    image: '/images/news/kosten-bouwploeg-per-uur.webp',
    blocks: [
        { type: 'p', text: 'Twee offertes voor "een ploeg van vier" kunnen er identiek uitzien en toch een verschil van tienduizenden euro\'s op uw project betekenen. Het verschil zit zelden in het uurtarief dat bovenaan staat, maar in wat er wel en niet in dat tarief zit — en in wat er gebeurt als de omstandigheden veranderen.' },
        { type: 'h2', text: 'Waar een all-in uurprijs uit bestaat' },
        { type: 'p', text: 'Een realistisch all-in tarief is opgebouwd uit meerdere lagen. Wie alleen naar het brutoloon kijkt, vergeet doorgaans de helft van de kost.' },
        { type: 'ul', items: [
            'Brutoloon of nettovergoeding van de vakmensen, inclusief vakantiegeld en eindejaarspremie.',
            'Sociale lasten en verzekeringen: patronale bijdragen, arbeidsongevallenverzekering, waarborg.',
            'Verplaatsing en verblijf: transport van en naar de werf, overnachting, maaltijdvergoeding.',
            'Gereedschap en verbruik: handgereedschap, machines, persoonlijke beschermingsmiddelen, verbruiksartikelen.',
            'Administratie en compliance: A1, Limosa, Checkinatwork, loonadministratie, sociaal secretariaat.',
            'Risico en marge: vervanging bij ziekte, wachtdagen, uitvoeringsgarantie, coördinatie en opvolging.',
        ] },
        { type: 'p', text: 'Een tarief dat alleen het eerste punt dekt, is geen tarief — het is een aanbetaling. De rest komt terug op de eindafrekening, meestal op het moment dat u geen onderhandelingsruimte meer heeft.' },
        { type: 'h2', text: 'Waarom tarieven per project, regio en seizoen verschillen' },
        { type: 'p', text: 'Dezelfde ploeg kan in het voorjaar een ander tarief vragen dan in december, en een ploeg in een drukke stedelijke regio zit anders in de markt dan een ploeg in een landelijke omgeving. factoren die het tarief structureel beïnvloeden: de schaarste aan een specifiek vak, de reisafstand, de vraag of nacht- of weekendwerk nodig is, en de looptijd van de opdracht — een opdracht van zes maanden laat zich anders prijzen dan een opdracht van twee weken.' },
        { type: 'p', text: 'Vraag daarom altijd een indicatie voor de volledige looptijd van uw project, inclusief de periodes waarin u minder of geen mensen nodig heeft. Dat geeft een veel eerlijker beeld dan een enkel uurtarief.' },
        { type: 'h2', text: 'Hoe u offertes eerlijk vergelijkt' },
        { type: 'p', text: 'De enige betrouwbare vergelijking is een vergelijking op dezelfde scope. Gebruik dezelfde specificatie, dezelfde periode en dezelfde aantallen, en stel elke aanbieder dezelfde vragen.' },
        { type: 'ul', items: [
            'Wat is exact inbegrepen in het uurtarief, en wat wordt apart gefactureerd?',
            'Wie draagt de kosten van verplaatsing, verblijf en materiaal?',
            'Hoe worden overuren, wachtdagen en niet-productieve dagen afgerekend?',
            'Wat gebeurt er bij ziekte of uitval — en binnen welke termijn is er vervanging?',
            'Welke attesten en documenten zitten in de prijs, en welke moet u zelf regelen?',
            'Geldt het tarief voor de volledige looptijd, of is een indexering voorzien?',
        ] },
        { type: 'p', text: 'Zet de antwoorden in één tabel naast elkaar. Wat u zoekt is niet de laagste regel, maar de aanbieder met de minste onbekenden.' },
        { type: 'quote', text: 'Een tarief is pas vergelijkbaar als u weet wat er niet in zit.' },
        { type: 'h2', text: 'Reken ook de kosten van een slechte match mee' },
        { type: 'p', text: 'De duurste ploeg is niet de ploeg met het hoogste tarief, maar de ploeg die na twee weken vervangen moet worden. Reken bij een wissel niet alleen het nieuwe tarief mee, maar ook de stilstand, de extra inwerkingsperiode, de herkeuring van werk en de vertraging in uw planning.' },
        { type: 'p', text: 'Daarom is een expliciete proefperiode met duidelijke criteria een kosteninstrument, geen formaliteit. U betaalt een korte periode om te vermijden dat u maanden aan een slechte match vastzit.' },
        { type: 'h2', text: 'Praktische conclusie' },
        { type: 'ul', items: [
            'Vergelijk altijd op gespecificeerde opbouw, niet op één uurtarief.',
            'Vraag wat expliciet niet inbegrepen is — daar zit het verschil.',
            'Reken de kosten van vervanging en stilstand mee in uw beslissing.',
            'Spreek de proefperiode en de opzegmodaliteiten vooraf af.',
        ] },
        { type: 'p', text: 'Wie deze vier regels hanteert, koopt capaciteit tegen een voorspelbare prijs in plaats van een goedkope start met een dure afloop.' },
    ],
    related: [
        { label: 'Onderaannemer bouw inhuren: waar u op moet letten', href: '/nieuws/onderaannemer-bouw-inhuren' },
        { label: 'A1 en Limosa: wat u moet checken vóór een ploeg start', href: '/nieuws/a1-limosa-check-hoofdaannemer' },
        { label: 'Gescreende bouwploegen voor aannemers', href: '/werkgevers' },
    ],
    cta: {
        title: 'Een prijs op maat voor uw project?',
        text: 'Vertel ons welke ploeg u nodig heeft en voor hoe lang — u krijgt een gespecificeerde opbouw in plaats van een los uurtarief.',
        label: 'Vraag een ploeg aan',
        href: '/werkgevers',
    },
};
