import type { Article } from '../types';

export const article: Article = {
    slug: 'onderaannemer-bouw-inhuren',
    title: 'Onderaannemer bouw inhuren: waar een hoofdaannemer op moet letten',
    description:
        'Van prijsopbouw tot legaliteit en opstarttermijn: de praktische checklist die u als hoofdaannemer doorloopt voordat u een onderaannemer of bouwploeg inschakelt.',
    date: '2026-08-10',
    updated: '2026-08-18',
    author: 'Constructief',
    authorIsOrganization: true,
    category: 'Inkoop & compliance',
    keywords: ['onderaannemer bouw inhuren', 'bouwploeg inhuren', 'onderaanneming checklist'],
    readingMinutes: 7,
    blocks: [
        { type: 'p', text: 'Een onderaannemer inschakelen lijkt een simpele inkoopbeslissing: u heeft capaciteit nodig, iemand levert mensen, de werf loopt door. In de praktijk bepaalt de manier waarop u die ploeg selecteert of u aan het einde van het project winst maakt of een juridisch dossier rijker bent. Deze gids zet op een rij waar hoofdaannemers in België en Nederland het vaakst op vastlopen.' },
        { type: 'h2', text: '1. Bepaal eerst welk type samenwerking u nodig heeft' },
        { type: 'p', text: 'Onderaanneming, detachering en payroll zijn geen synoniemen, en ze verschillen sterk in wie het werkgeversrisico draagt. Kies bewust voordat u prijzen vergelijkt, anders vergelijkt u appels met peren.' },
        { type: 'ul', items: [
            'Onderaanneming: de ploeg werkt voor eigen rekening en levert een resultaat. U koopt een uitkomst, geen uren.',
            'Detachering: buitenlandse werknemers blijven in dienst van hun eigen werkgever, maar werken op uw werf.',
            'Payroll / uitlening: u leent personeel in en draagt zelf de aansturing; de loonadministratie loopt via een derde.',
        ] },
        { type: 'p', text: 'De juridische en financiële gevolgen van een verkeerde keuze zijn groot. Wie feitelijk leiding geeft aan andermans werknemers zonder dat dit contractueel klopt, riskeert herkwalificatie van de samenwerking met alle sociale en fiscale gevolgen van dien.' },
        { type: 'h2', text: '2. Vraag een gespecificeerde prijsopbouw, niet alleen een uurtarief' },
        { type: 'p', text: 'Een all-in uurprijs zegt weinig als u niet weet wat erin zit. Vraag altijd om een opbouw waarin loon, sociale lasten, verplaatsing, verblijf, materiaal en administratie apart staan. Zo ziet u meteen waar een ogenschijnlijk goedkoop tarief zijn kosten verbergt.' },
        { type: 'ul', items: [
            'Is het tarief inclusief of exclusief sociale lasten en verzekeringen?',
            'Zijn verplaatsing, overnachting en maaltijden inbegrepen of apart gefactureerd?',
            'Wie levert gereedschap, verbruiksartikelen en persoonlijke beschermingsmiddelen?',
            'Hoe worden overuren, wachturen en regendagen afgerekend?',
        ] },
        { type: 'p', text: 'Vergelijk minimaal drie partijen op exact dezelfde scope. Eén extra kolom in uw vergelijking — "wat is expliciet niet inbegrepen" — voorkomt de meeste discussies achteraf.' },
        { type: 'h2', text: '3. Verifieer de legaliteit vóór de eerste werkdag' },
        { type: 'p', text: 'Dit is het onderdeel dat het vaakst wordt overgeslagen en achteraf het duurst is. Een ploeg die morgen kan starten maar geen papieren heeft, is geen koopje: bij een controle bent u als hoofdaannemer in België mee verantwoordelijk voor de naleving op uw werf.' },
        { type: 'ul', items: [
            'A1-verklaring per werknemer: bewijs dat de sociale zekerheid van het thuisland van toepassing is.',
            'Limosa-melding voor detachering en voor zelfstandigen die in België komen werken.',
            'Checkinatwork-registratie op de werf zelf, per dag en per persoon.',
            'Identiteitsdocumenten, beroepsattesten en een polis arbeidsongevallen op naam van de werkgever.',
        ] },
        { type: 'p', text: 'Vraag deze documenten op vóór de start en controleer of de namen op de attesten overeenkomen met de mensen die effectief op de werf staan. Wat u vraagt, moet u ook kunnen tonen als de inspectie langskomt.' },
        { type: 'quote', text: 'De goedkoopste ploeg is zelden de ploeg die u het minst kost.' },
        { type: 'h2', text: '4. Spreek een proefperiode af in plaats van te gokken' },
        { type: 'p', text: 'Een kennismaking op kantoor zegt weinig over hoe een ploeg op uw werf presteert. Bouw daarom een expliciete proefperiode in — bijvoorbeeld een testweek van veertien dagen — met vooraf afgesproken criteria: tempo, kwaliteit van de afwerking, veiligheidsgedrag, communicatie met uw eigen ploegbaas en opvolging van instructies.' },
        { type: 'p', text: 'Leg vast wat er gebeurt als de samenwerking niet klikt: welke opzegtermijn geldt, wie draagt de kosten van de wissel, en hoe snel is er vervanging. Dat maakt een proefperiode een echt beslissingsinstrument in plaats van een formaliteit.' },
        { type: 'h2', text: '5. Regel de opstarttermijn realistisch in' },
        { type: 'p', text: 'De grootste vertragingen ontstaan niet op de werf maar in de aanloop: attesten, huisvesting, vervoer en materiaaltransport. Reken voor een nieuwe ploeg een realistische opstarttermijn in en plan de eerste dagen bewust in als inwerktijd op uw eigen afspraken en veiligheidsprocedures.' },
        { type: 'ul', items: [
            'Bevestig de exacte startdatum schriftelijk, inclusief uur en locatie.',
            'Regel huisvesting of verblijf vóór de eerste dag, niet erna.',
            'Voorzie een korte inwerkingssessie over werfinstructies en veiligheidsregels.',
            'Wijs één aanspreekpunt aan bij uzelf en één bij de ploeg.',
        ] },
        { type: 'h2', text: '6. Leg afspraken vast die u ook echt kunt afdwingen' },
        { type: 'p', text: 'Een mondelinge afspraak met een ploegbaas verdwijnt zodra er vertraging of discussie komt. Zet in het contract minimaal vast: scope en resultaat, tarief en betaaltermijn, wie welke documenten levert, de proefperiode met criteria, de opzegmodaliteiten, en wat er gebeurt bij ziekte of uitval.' },
        { type: 'p', text: 'Wie deze zes stappen doorloopt, koopt capaciteit in plaats van problemen. Het kost een paar uur voorbereiding en bespaart doorgaans een veelvoud daarvan op de werf.' },
    ],
    related: [
        { label: 'A1 en Limosa: wat u moet checken vóór een ploeg start', href: '/nieuws/a1-limosa-check-hoofdaannemer' },
        { label: 'Wat bepaalt de prijs van een bouwploeg per uur?', href: '/nieuws/kosten-bouwploeg-per-uur' },
        { label: 'Gescreende bouwploegen voor aannemers', href: '/werkgevers' },
    ],
    cta: {
        title: 'Een ploeg nodig voor uw volgende werf?',
        text: 'Wij leveren gescreende, legale bouwploegen met A1 en Limosa geregeld — inclusief 14-dagen testweek en vergoeding op resultaat.',
        label: 'Bekijk onze aanpak voor aannemers',
        href: '/werkgevers',
    },
};
