import type { Article } from '../types';

export const article: Article = {
    slug: 'zwartwerk-vermijden-checklist',
    title: 'Zwartwerk op de werf vermijden: checklist voor aannemers',
    description:
        'Zwartwerk op uw werf kost u meer dan een boete. Met deze controlelijst verifieert u een onderaannemer vóór de start en houdt u uw eigen dossier op orde.',
    date: '2026-08-16',
    updated: '2026-08-18',
    author: 'Constructief',
    authorIsOrganization: true,
    category: 'Risico & compliance',
    keywords: ['zwartwerk bouw', 'illegale tewerkstelling', 'controle onderaannemer'],
    readingMinutes: 6,
    blocks: [
        { type: 'p', text: 'Illegale tewerkstelling op een bouwwerf is zelden het werk van één persoon. Ze ontstaat meestal in een keten: een hoofdaannemer die onder tijdsdruk een ploeg aanneemt, een tussenpartij die de administratie "regelt", en een ploeg die effectief op de werf staat zonder dat iemand de documenten echt heeft gecontroleerd.' },
        { type: 'p', text: 'De gevolgen komen terecht bij de partij die het minst heeft gecontroleerd. Daarom is verificatie geen bureaucratie maar risicobeheer.' },
        { type: 'h2', text: 'Wat er op het spel staat' },
        { type: 'ul', items: [
            'Fiscale en sociale sancties, oplopend met de ernst en de duur van de overtreding.',
            'Solidariteit voor achterstallige lonen wanneer de keten niet in orde is.',
            'Stillegging van de werf, met alle plannings- en kostenimpact vandien.',
            'Reputatieschade bij opdrachtgevers en bij aanbestedingen.',
            'Aansprakelijkheid wanneer een niet-verzekerde werknemer een arbeidsongeval krijgt.',
        ] },
        { type: 'p', text: 'Een werf stilleggen kost al snel meer dan het volledige jaarbudget van een inkoopcontrole. Toch is dat precies wat er gebeurt wanneer niemand de documenten heeft opgevraagd.' },
        { type: 'h2', text: 'Checklist vóór de eerste werkdag' },
        { type: 'p', text: 'Loop deze lijst door bij elke nieuwe ploeg, ook wanneer u de partij al langer kent. Vertrouwen is geen document.' },
        { type: 'ul', items: [
            'Identiteit: geldig identiteitsdocument van elke persoon die op de werf komt.',
            'A1-verklaring per werknemer, met kloppende naam en geldige periode.',
            'Limosa-melding met de juiste werf, periode en personen — aangemeld vóór de start.',
            'Checkinatwork: registratie geregeld en afspraken over wie dagelijks in- en uitcheckt.',
            'Verzekering arbeidsongevallen op naam van de werkgever, met bewijs van betaling.',
            'Ondernemingsnummer en, waar van toepassing, inschrijving en beroepsattesten.',
            'Getekende overeenkomst met scope, tarief, proefperiode en opzegmodaliteiten.',
            'Bewijs dat u zelf heeft gecontroleerd: een kopie per document, per ploeg.',
        ] },
        { type: 'p', text: 'Controleer niet alleen of de documenten bestaan, maar of ze kloppen met de realiteit op de werf. De meest voorkomende vaststelling is niet een ontbrekend document, maar een document dat iemand anders betreft dan wie er werkt.' },
        { type: 'h2', text: 'Signalen die om extra controle vragen' },
        { type: 'ul', items: [
            'Een ploeg die binnen 24 uur kan starten zonder dat er documenten gevraagd worden.',
            'Een tarief dat structureel onder de markt ligt zonder verklaarbare opbouw.',
            'Werknemers die op de werf blijven terwijl hun opgegeven periode is afgelopen.',
            'Facturatie via een andere partij dan de werkgever op de attesten.',
            'Weerstand tegen dagelijkse registratie of tegen het tonen van identiteitsbewijzen.',
        ] },
        { type: 'p', text: 'Geen van deze signalen is op zichzelf een bewijs van een overtreding. Samen zijn ze een reden om niet te starten voordat alles klopt.' },
        { type: 'quote', text: 'Uitbesteden betekent niet dat u de verantwoordelijkheid uitbesteedt.' },
        { type: 'h2', text: 'Zo houdt u het vol op lange termijn' },
        { type: 'p', text: 'De werkwijze die het beste standhoudt is er een waarbij de controle niet afhangt van de ijver van één persoon. Maak een vaste documentenlijst, gebruik dezelfde werkwijze bij elke ploeg, en bewaar alles op één plaats per project.' },
        { type: 'ul', items: [
            'Standaardiseer de opvraag: dezelfde lijst, bij elke nieuwe partij.',
            'Koppel de start van de werken aan de volledigheid van het dossier.',
            'Blijf controleren bij elke wijziging in de ploegsamenstelling.',
            'Bewaar documenten inclusief versies en data, niet alleen het eindresultaat.',
        ] },
        { type: 'p', text: 'Werken met ploegen die hun compliance zelf aantoonbaar op orde hebben, is de eenvoudigste manier om dit risico structureel te verlagen. Het maakt de controle kort, voorspelbaar en verdedigbaar.' },
    ],
    related: [
        { label: 'A1 en Limosa: wat u moet checken vóór een ploeg start', href: '/nieuws/a1-limosa-check-hoofdaannemer' },
        { label: 'Onderaannemer bouw inhuren: waar u op moet letten', href: '/nieuws/onderaannemer-bouw-inhuren' },
        { label: 'Gescreende bouwploegen voor aannemers', href: '/werkgevers' },
    ],
    cta: {
        title: 'Legale ploegen, met het papierwerk geregeld',
        text: 'Wij leveren ploegen waarvan A1, Limosa en Checkinatwork vooraf in orde zijn — u hoeft alleen te controleren, niet te jagen.',
        label: 'Bekijk onze aanpak voor aannemers',
        href: '/werkgevers',
    },
};
