import { getTranslations, setRequestLocale } from 'next-intl/server';
import { Link } from '@/i18n/routing';
import { Button } from '@/components/ui/button';
import { EmployerUSP } from '@/components/sections/EmployerUSP';
import { WerkgeversLink } from '@/components/sections/WerkgeversLink';
import { citiesData, flagshipCitySlugs } from '@/data/cities';
import { CheckCircle2, ChevronRight, Home, Layers, Wrench, Building2 } from 'lucide-react';

/**
 * Nation-wide (city-agnostic) trade landing — the "hub" page for a trade across
 * all flagship cities. Reads the unique `TradeNation.<trade>` copy (generated by
 * Agent 3) so it is NOT a reworded copy of a city page, and links down to the
 * per-city trade pages (internal linking + distinct content).
 */
export async function TradeLanding({
  trade,
  locale,
}: {
  trade: string;
  locale: string;
}) {
  setRequestLocale(locale);

  const tN = await getTranslations({ locale, namespace: 'TradeNation' });
  const tNav = await getTranslations({ locale, namespace: 'Navigation' });

  const title = tN(`${trade}.title`);
  const intro = tN(`${trade}.intro`);
  const sectionTitle = tN(`${trade}.section_title`);
  const features = (tN.raw(`${trade}.features`) as string[]) ?? [];
  const ctaTitle = tN(`${trade}.cta_title`);
  const ctaDesc = tN(`${trade}.cta_desc`);
  const ctaButton = tN(`${trade}.cta_button`);

  const cityLinks = flagshipCitySlugs.map((slug) => ({
    slug,
    name: citiesData.find((c) => c.slug === slug)?.name ?? slug,
  }));

  return (
    <div className="flex flex-col min-h-screen">
      {/* Breadcrumb */}
      <nav aria-label={tNav('home')} className="container py-4 text-sm text-muted-foreground">
        <ol className="flex flex-wrap items-center gap-1.5">
          <li>
            <Link href="/" className="inline-flex items-center gap-1 hover:text-primary">
              <Home className="w-3.5 h-3.5" />
              {tNav('home')}
            </Link>
          </li>
          <li aria-hidden="true">
            <ChevronRight className="w-3.5 h-3.5" />
          </li>
          <li>
            <Link href="/diensten" className="hover:text-primary">
              {tNav('regions')}
            </Link>
          </li>
          <li aria-hidden="true">
            <ChevronRight className="w-3.5 h-3.5" />
          </li>
          <li className="font-medium text-neutral-900" aria-current="page">
            {title}
          </li>
        </ol>
      </nav>

      {/* Hero */}
      <section className="relative overflow-hidden bg-neutral-900 py-28 md:py-36">
        <div className="absolute inset-0 z-0 bg-[#0a0f1a]"></div>
        <div className="absolute inset-0 opacity-40">
          <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-blue-600 blur-[120px]"></div>
          <div className="absolute bottom-[10%] right-[-5%] w-[30%] h-[30%] rounded-full bg-accent blur-[100px] opacity-30"></div>
        </div>
        <div className="container relative z-10 flex flex-col items-center text-center">
          <div className="flex items-center gap-2 text-primary mb-5">
            <Layers className="w-6 h-6" />
            <span className="uppercase tracking-wide font-semibold text-sm">{title}</span>
          </div>
          <h1 className="max-w-4xl text-4xl font-bold tracking-tight text-white sm:text-5xl md:text-6xl mb-6 leading-tight">
            {title}
          </h1>
          <p className="max-w-2xl text-lg text-neutral-200 mb-10 leading-relaxed">{intro}</p>
          <Button asChild size="lg" className="text-lg px-8 py-6 rounded-full bg-white text-neutral-900 hover:bg-blue-50 hover:scale-105 transition-all duration-300 shadow-xl shadow-blue-500/10">
            <Link href="/werkgevers">
              {ctaButton}
              <ChevronRight className="ml-2 w-5 h-5" />
            </Link>
          </Button>
        </div>
      </section>

      {/* What the teams deliver */}
      <section className="py-20 px-4 md:px-8 bg-white">
        <div className="container max-w-5xl">
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 text-primary mb-3">
              <Wrench className="w-5 h-5" />
              <span className="font-semibold">{sectionTitle}</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-neutral-900">{sectionTitle}</h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {features.map((feature, i) => (
              <div key={i} className="bg-neutral-50 p-6 rounded-2xl border border-neutral-100 flex items-start gap-4">
                <CheckCircle2 className="w-6 h-6 text-primary shrink-0 mt-0.5" />
                <p className="text-neutral-700 font-medium">{feature}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Where we work — unique hub section with internal links to city trade pages */}
      <section className="py-20 px-4 md:px-8 bg-neutral-50">
        <div className="container max-w-5xl">
          <div className="text-center mb-8">
            <div className="inline-flex items-center gap-2 text-primary mb-3">
              <Building2 className="w-5 h-5" />
              <span className="font-semibold">{tNav('regions')}</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-neutral-900">
              {title}
            </h2>
          </div>
          <div className="flex flex-wrap justify-center gap-4">
            {cityLinks.map((c) => (
              <Link
                key={c.slug}
                href={`/diensten/onderaannemer-${trade}-${c.slug}`}
                className="inline-flex items-center gap-2 rounded-full border border-neutral-200 bg-white px-5 py-2.5 font-medium text-neutral-800 hover:bg-neutral-100 transition-colors"
              >
                <Building2 className="w-4 h-4 text-primary" />
                {c.name}
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Trust / compliance / testweek / pay-for-result proof */}
      <EmployerUSP />

      {/* Contextual internal link to the commercial flagship /werkgevers */}
      <WerkgeversLink locale={locale} />

      {/* CTA */}
      <section className="py-24 px-4 md:px-8 bg-primary text-white text-center">
        <div className="container max-w-3xl">
          <h2 className="text-3xl md:text-5xl font-bold mb-6">{ctaTitle}</h2>
          <p className="text-xl mb-10 opacity-90 max-w-2xl mx-auto text-white/90">{ctaDesc}</p>
          <Button asChild size="lg" variant="secondary" className="text-lg px-10 py-6 rounded-full bg-white text-neutral-900 hover:bg-blue-50 hover:scale-105 transition-all duration-300 shadow-xl shadow-blue-500/10 border-0">
            <Link href="/contact">
              {ctaButton}
              <ChevronRight className="ml-2 w-5 h-5" />
            </Link>
          </Button>
        </div>
      </section>
    </div>
  );
}
